### ISSUE TITLE
Develop a printed circuit board (PCB) for the chassis controller (Discovery).

### ISSUE THREAD

**Issue by AksonovSergei** [KPI-Rover/ecu_hw#1]
It is necessary to develop a printed circuit board (PCB) for the chassis controller.
The general functional system diagram: https://kpi-rover.github.io/docs/platform/overview/
The PCB requirements can be found by the following link: https://kpi-rover.github.io/docs/platform/ecu/requirements-chassis-ecu-stm32

**Task sequence:**
1. Review the requirements, clarify any unclear details, and supplement if necessary.
2. Assign MCU's pins. Should be done in scope of the issue: https://github.com/KPI-Rover/ecu_sw/issues/12
3. Develop the electrical schematic and coordinate with the project participants.
4. Design the PCB outline, place key components, and coordinate with the project participants.
7. Perform the PCB routing.
8. Prepare the set of files for production ordering.
9. Prepare the list of components for ordering.
10. Solder and bring up PCB

**Comment by AksonovSergei** [comment]
Зверніть увагу що я додав нові вимоги до плати.

**Comment by AksonovSergei** [comment]
Hi @nazarbychkar 
Please review the task and requirements specification. Be ready to discus on this Wednesday meeting.

**Comment by AksonovSergei** [comment]
Hi @Rhinemann and @nazarbychkar ,
How's it going? If you have any questions or need support, please ask in this task.

**Comment by AksonovSergei** [comment]
@Rhinemann @nazarbychkar 
I suggest to use for Ethernet: https://www.lcsc.com/product-detail/Ethernet-Transceivers_Microchip-Tech-KSZ8081RNBIA-TR_C100018.html?s_z=n_KSZ8081RNB
It is replacement for one is used on GL Embedded KIT.
https://github.com/GlobalLogicEdu/GL-SK-BSP/blob/master/Documentation/Schematic_1.1.pdf

**Comment by AksonovSergei** [comment]
Hi @nazarbychkar 
I have reviewed schematic and found that we did not update DC-DC converter according to last changest in it.
Please reffer to https://github.com/KPI-Rover/rpi-power-hat/tree/Releases/Version1.1 
Please replace Q15, C58-C60, L4 with exactly the same components like in rpi-power-hat.

**Comment by AksonovSergei** [comment]
@nazarbychkar 
I have updated STM32 pins assignment to be compatible with Discovery board. 
I will ask SW developers to check it and after that I will ask you to make changes in schematic.
Please put layout on pause.

**Comment by AksonovSergei** [comment]
Hi @nazarbychkar 
1. Since we have not anought pins, we should remove one serial interface

<img width="302" height="281" alt="Image" src="https://github.com/user-attachments/assets/bc5994e7-8cdf-4221-802d-b03c428ff828" />

2. Use the following pinout for J7 to connect the ECU board and the RPI with a straight cable.
1 - GND
2 - TX
3 - RX

**Comment by AksonovSergei** [comment]
@nazarbychkar 
We have one more problem. We do not have enough timers to implement PWM using MCU. That's why we should use external PWM driver NXP PCA9685PW.  We do not need output transistors in this case.
https://www.lcsc.com/product-detail/C2678753.html?s_z=n_PCA9685


Please use 4 PWMs for motors and all other connect to headers like it is done here:
https://learn.adafruit.com/16-channel-pwm-servo-driver/downloads

**Comment by AksonovSergei** [comment]
@nazarbychkar 

<img width="1167" height="1163" alt="Image" src="https://github.com/user-attachments/assets/3b032e1c-0274-4567-bd74-d665fdccc70b" />

**Comment by AksonovSergei** [comment]
Hi @nazarbychkar 

1. Please make mounting holes like it is done for the RPI Power HAT
https://github.com/KPI-Rover/rpi-power-hat
2. Do not display components values on PCB
3. Please fix all Unconnected Items and check Errors

<img width="728" height="587" alt="Image" src="https://github.com/user-attachments/assets/540b5eb0-0990-43fa-a181-15d014fe8642" />
4. Please place all SMD components on one side opposite to the Discovery board. DC-DC converter on the correct side.

<img width="875" height="593" alt="Image" src="https://github.com/user-attachments/assets/0bb7cc97-b414-406f-a0af-75f3178a75e5" />

<img width="611" height="553" alt="Image" src="https://github.com/user-attachments/assets/574cc750-6ee6-4220-8fc5-a75295b693ce" />

**Comment by AksonovSergei** [comment]
Review comments

- [x] Short circuit between input voltage and DC-DC output

<img width="1243" height="588" alt="Image" src="https://github.com/user-attachments/assets/f7c3eadf-7c4c-452f-a417-415d12f0c20e" />

- [x] SMD components smaller then 0805 are used. It will be very hard to solder so small components. I suggest to use all components 0805 expect C1, C6, C7, C8
- [x] References location should be fixed. For a lot of components it is hard to understand where is its reference. Also references are on pads. 

<img width="938" height="389" alt="Image" src="https://github.com/user-attachments/assets/c68709eb-2f02-4589-9ba2-b3a6e37313b6" />

<img width="734" height="382" alt="Image" src="https://github.com/user-attachments/assets/395ebf55-4815-40b4-a8a5-597d745f81d4" />

- [x] `TTL_TX` should be connected to pin `PD8`  and `TTL_RX` should be connected to `PB11`

**Comment by AksonovSergei** [comment]
- [x] We lost the schematic to measure input voltage. We need to connect VCC (12V) to POWER_SUPPLY_ADC through a resistor divider.

**Comment by AksonovSergei** [comment]
- [x] Wrong signal on the input voltage connector

<img width="740" height="431" alt="Image" src="https://github.com/user-attachments/assets/c3767d0f-78f9-4c68-919c-7e3fcfa3cba1" />

**Comment by AksonovSergei** [comment]
Please update schematic based on bring up
